CREATE TABLE [dbo].[tAlertasRiesgoCliente] (
  [Id] [int] IDENTITY,
  [CodUsuario] [varchar](15) NOT NULL,
  [NroSolicitud] [varchar](15) NOT NULL,
  [CodOficina] [varchar](4) NOT NULL,
  [TipoPersona] [varchar](3) NULL,
  [PuntTipoPersona] [decimal](10, 3) NULL,
  [ZonaGeografica] [int] NULL,
  [PuntZonaGeografica] [decimal](10, 3) NULL,
  [CodPais] [varchar](4) NULL,
  [Pais] [varchar](40) NULL,
  [PuntPais] [decimal](10, 3) NULL,
  [Edad] [int] NULL,
  [PuntEdad] [decimal](10, 3) NULL,
  [InstrumentoMonetario] [int] NULL,
  [PuntInstrumentoMonetario] [decimal](10, 3) NULL,
  [SaldoCuenta] [money] NULL,
  [PuntMontoInversion] [decimal](10, 3) NULL,
  [RiesgoActividadEconomica] [varchar](5) NULL,
  [PuntActividadEconomica] [decimal](10, 3) NULL,
  [RiesgoOrigenRecursos] [varchar](5) NULL,
  [PuntOrigenRecursos] [decimal](10, 3) NULL,
  [IdProducto] [int] NULL,
  [PuntTipoProducto] [decimal](10, 3) NULL,
  [EsPPE] [int] NULL,
  [ParentescoPPE] [int] NULL,
  [PuntPPE] [decimal](10, 3) NULL,
  [PuntTotal] [decimal](10, 3) NULL,
  [RiesgoTotal] [varchar](5) NULL,
  [Activo] [int] NOT NULL DEFAULT (1),
  [RptaRegla] [int] NOT NULL DEFAULT (0),
  [DictamenObservacion] [varchar](500) NULL,
  [CodSistema] [varchar](3) NOT NULL,
  [FechaRespuesta] [datetime] NULL,
  [FechaRegistro] [datetime] NOT NULL DEFAULT (getdate()),
  [FechaActualizacion] [datetime] NULL,
  CONSTRAINT [PK_tAlertasRiesgoCliente] PRIMARY KEY CLUSTERED ([Id])
)
ON [PRIMARY]
GO