CREATE TABLE [dbo].[tBcMonitorRespCuentas] (
  [IdMonitor] [int] NOT NULL,
  [IdCuenta] [int] IDENTITY,
  [FechaActualizacion] [varchar](8) NULL,
  [RegistroImpugnado] [varchar](4) NULL,
  [ClaveUsuario] [varchar](10) NULL,
  [NombreUsuario] [varchar](16) NULL,
  [TelefonoUsuario] [varchar](11) NULL,
  [CreditoActual] [varchar](25) NULL,
  [TipoResponsabilidad] [varchar](1) NULL,
  [TipoCuenta] [varchar](1) NULL,
  [TipoContrato] [varchar](2) NULL,
  [MonedaCredito] [varchar](2) NULL,
  [ImporteAvaluo] [varchar](9) NULL,
  [NumeroPagos] [varchar](4) NULL,
  [FrecuenciaPagos] [varchar](1) NULL,
  [MontoPagar] [varchar](9) NULL,
  [FechaApertura] [varchar](8) NULL,
  [FechaUltimoPago] [varchar](8) NULL,
  [FechaUltimaCompra] [varchar](8) NULL,
  [FechaCierre] [varchar](8) NULL,
  [FechaReporteInfo] [varchar](8) NULL,
  [ModoReportar] [varchar](1) NULL,
  [UltFecSaldoCero] [varchar](8) NULL,
  [Garantia] [varchar](40) NULL,
  [CredMaxAutorizado] [varchar](9) NULL,
  [SaldoActual] [varchar](10) NULL,
  [LimiteCredito] [varchar](9) NULL,
  [SaldoVencido] [varchar](9) NULL,
  [NumPagosVencidos] [varchar](4) NULL,
  [MOP] [varchar](2) NULL,
  [HistoricoPagos] [varchar](72) NULL,
  [FecRecienteHistPag] [varchar](8) NULL,
  [FecAntiguaHistPag] [varchar](8) NULL,
  [ClaveObservacion] [varchar](2) NULL,
  [TotaPagosReportados] [varchar](3) NULL,
  [TotalPagosMOP02] [varchar](2) NULL,
  [TotalPagosMOP03] [varchar](2) NULL,
  [TotalPagosMOP04] [varchar](2) NULL,
  [TotalPagosMOP05Mas] [varchar](2) NULL,
  [SaldoMorosidadHistAlta] [varchar](9) NULL,
  [FecMorosidadHistAlta] [varchar](8) NULL,
  [MOPMorosidadAlta] [varchar](2) NULL,
  [FecIniReestructura] [varchar](8) NULL,
  [MontoUltPago] [varchar](9) NULL,
  CONSTRAINT [PK_tBcMonitorRespCuentas] PRIMARY KEY CLUSTERED ([IdMonitor], [IdCuenta])
)
ON [PRIMARY]
GO

GRANT SELECT ON [dbo].[tBcMonitorRespCuentas] TO [public]
GO