CREATE TABLE [dbo].[tLpCliente] (
  [IdCliente] [int] IDENTITY,
  [IdProceso] [int] NOT NULL,
  [APaterno] [varchar](20) NULL,
  [AMaterno] [varchar](20) NULL,
  [Nombres] [varchar](20) NULL,
  [FecNacimiento] [smalldatetime] NULL,
  [CodDocIden] [varchar](4) NULL,
  [DI] [varchar](20) NULL,
  [CodEstadoCivil] [varchar](1) NULL,
  [Genero] [varchar](1) NULL,
  [FamiliarNegocio] [varchar](1) NULL,
  [Direccion] [varchar](150) NULL,
  [NumExterno] [varchar](10) NULL,
  [NumInterno] [varchar](10) NULL,
  [Ubicacion] [varchar](150) NULL,
  [CodPostal] [varchar](5) NULL,
  [localidad] [varchar](50) NULL,
  [EsPrincipal] [bit] NULL,
  [TiempoDirDesde] [smallint] NULL,
  [TiempoCiudad] [smallint] NULL,
  [Telefono] [varchar](20) NULL,
  [Observaciones] [varchar](250) NULL,
  [EstadoNacimiento] [varchar](10) NULL,
  [CURP] [varchar](30) NULL,
  [RFC] [varchar](20) NULL,
  [Celular] [varchar](50) NULL,
  [LabActividad] [varchar](50) NULL,
  [Correo] [varchar](50) NULL,
  [ClaveBancoSTP] [varchar](10) NULL,
  [CLABE] [varchar](20) NULL,
  [FechaAlta] [smalldatetime] NOT NULL,
  [CodUsAlta] [varchar](20) NOT NULL,
  CONSTRAINT [PK_tLpCliente] PRIMARY KEY CLUSTERED ([IdCliente])
)
ON [PRIMARY]
GO